--------------------------------------------------------
--  File created - Friday-May-24-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table HMS_ROOM
--------------------------------------------------------

  CREATE TABLE "HR"."HMS_ROOM" 
   (	"ROOM_ID" NUMBER(5,0), 
	"ROOM_TYPE" VARCHAR2(30 BYTE), 
	"PRICE" NUMBER(10,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into HR.HMS_ROOM
SET DEFINE OFF;
Insert into HR.HMS_ROOM (ROOM_ID,ROOM_TYPE,PRICE) values (1,'king Bed',5999);
Insert into HR.HMS_ROOM (ROOM_ID,ROOM_TYPE,PRICE) values (2,'Twin Bed',4999);
--------------------------------------------------------
--  DDL for Index HMS_ROOM_ID_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."HMS_ROOM_ID_PK" ON "HR"."HMS_ROOM" ("ROOM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C004174
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SYS_C004174" ON "HR"."HMS_ROOM" ("ROOM_TYPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table HMS_ROOM
--------------------------------------------------------

  ALTER TABLE "HR"."HMS_ROOM" ADD CONSTRAINT "HMS_ROOM_ID_PK" PRIMARY KEY ("ROOM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "HR"."HMS_ROOM" MODIFY ("ROOM_TYPE" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."HMS_ROOM" MODIFY ("PRICE" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."HMS_ROOM" ADD UNIQUE ("ROOM_TYPE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
