--------------------------------------------------------
--  File created - Friday-May-24-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table HMS_FACILITIES
--------------------------------------------------------

  CREATE TABLE "HR"."HMS_FACILITIES" 
   (	"FACILITIES_ID" NUMBER(5,0), 
	"FEATURES" VARCHAR2(30 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into HR.HMS_FACILITIES
SET DEFINE OFF;
Insert into HR.HMS_FACILITIES (FACILITIES_ID,FEATURES) values (100,'wifi');
Insert into HR.HMS_FACILITIES (FACILITIES_ID,FEATURES) values (101,'wifi,free breakfast,TV');
Insert into HR.HMS_FACILITIES (FACILITIES_ID,FEATURES) values (102,'AC');
Insert into HR.HMS_FACILITIES (FACILITIES_ID,FEATURES) values (103,'free parking');
Insert into HR.HMS_FACILITIES (FACILITIES_ID,FEATURES) values (104,'free breakfast');
Insert into HR.HMS_FACILITIES (FACILITIES_ID,FEATURES) values (105,'room service');
--------------------------------------------------------
--  DDL for Index HMS_FACILITIES_ID_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."HMS_FACILITIES_ID_PK" ON "HR"."HMS_FACILITIES" ("FACILITIES_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index FEATURES_CON
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."FEATURES_CON" ON "HR"."HMS_FACILITIES" ("FEATURES") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table HMS_FACILITIES
--------------------------------------------------------

  ALTER TABLE "HR"."HMS_FACILITIES" ADD CONSTRAINT "FEATURES_CON" UNIQUE ("FEATURES")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "HR"."HMS_FACILITIES" ADD CONSTRAINT "HMS_FACILITIES_ID_PK" PRIMARY KEY ("FACILITIES_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "HR"."HMS_FACILITIES" MODIFY ("FEATURES" NOT NULL ENABLE);
