--------------------------------------------------------
--  File created - Friday-May-24-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table HOTEL
--------------------------------------------------------

  CREATE TABLE "HR"."HOTEL" 
   (	"HOTEL_ID" NUMBER(6,0), 
	"NAME" VARCHAR2(50 BYTE), 
	"ROOM_ID" NUMBER(5,0), 
	"FACILITIES_ID" NUMBER(5,0), 
	"LOCATION" VARCHAR2(60 BYTE), 
	"CITY" VARCHAR2(30 BYTE), 
	"CONTACT_NO" NUMBER(10,0), 
	"NO_OF_ROOM" NUMBER(3,0), 
	"IMG_ID" NUMBER(*,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into HR.HOTEL
SET DEFINE OFF;
Insert into HR.HOTEL (HOTEL_ID,NAME,ROOM_ID,FACILITIES_ID,LOCATION,CITY,CONTACT_NO,NO_OF_ROOM,IMG_ID) values (1007,'Hotel Taj',1,105,'No. 2, Club House Road Chennai 600002','chennai',9963268492,30,7);
Insert into HR.HOTEL (HOTEL_ID,NAME,ROOM_ID,FACILITIES_ID,LOCATION,CITY,CONTACT_NO,NO_OF_ROOM,IMG_ID) values (1000,'Hotel Chainsys',1,100,'134,Mosque Street,C.Pallavaram(Near Airport),Chennai,TN','chennai',9597221466,50,1);
Insert into HR.HOTEL (HOTEL_ID,NAME,ROOM_ID,FACILITIES_ID,LOCATION,CITY,CONTACT_NO,NO_OF_ROOM,IMG_ID) values (1001,'Hotel Mepco',2,101,'CP 8 SIPCOT Industrial Park, Sriperumbudur,Tamil Nadu','chennai',9343256845,20,2);
Insert into HR.HOTEL (HOTEL_ID,NAME,ROOM_ID,FACILITIES_ID,LOCATION,CITY,CONTACT_NO,NO_OF_ROOM,IMG_ID) values (1002,'Hotel Meenakshi',2,101,'90/L, Maatuthavani,Madurai,Tamil Nadu','madurai',9343453465,60,4);
Insert into HR.HOTEL (HOTEL_ID,NAME,ROOM_ID,FACILITIES_ID,LOCATION,CITY,CONTACT_NO,NO_OF_ROOM,IMG_ID) values (1003,'TATA Hotel',1,103,'897, SIPCOT Industrial Park, Sriperumbudur,Tamil Nadu','chennai',9843253490,60,3);
Insert into HR.HOTEL (HOTEL_ID,NAME,ROOM_ID,FACILITIES_ID,LOCATION,CITY,CONTACT_NO,NO_OF_ROOM,IMG_ID) values (1004,'Hotel IBM',2,105,'34/R, Theni Highway, vandalur,Tamil Nadu','chennai',9243258492,70,5);
Insert into HR.HOTEL (HOTEL_ID,NAME,ROOM_ID,FACILITIES_ID,LOCATION,CITY,CONTACT_NO,NO_OF_ROOM,IMG_ID) values (1006,'Hotel Orange',1,105,'No. 80, Wallajah Road,Opp Kalaivanar Arangam,Chennai,TN','chennai',9989376854,80,6);
--------------------------------------------------------
--  DDL for Index HOTEL_ID_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."HOTEL_ID_PK" ON "HR"."HOTEL" ("HOTEL_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C004180
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SYS_C004180" ON "HR"."HOTEL" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C004181
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SYS_C004181" ON "HR"."HOTEL" ("CONTACT_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table HOTEL
--------------------------------------------------------

  ALTER TABLE "HR"."HOTEL" ADD CONSTRAINT "HOTEL_ID_PK" PRIMARY KEY ("HOTEL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "HR"."HOTEL" MODIFY ("NAME" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."HOTEL" MODIFY ("LOCATION" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."HOTEL" MODIFY ("CITY" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."HOTEL" MODIFY ("CONTACT_NO" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."HOTEL" ADD UNIQUE ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "HR"."HOTEL" ADD UNIQUE ("CONTACT_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
